---
title: "02_Run_Sims.qmd"
format: html
---

```{r}
#| echo: true
#| warning: false
#| message: false

rm(list=ls())

library(tidyverse)
library(readxl)
library(openxlsx)
library(purrr)
library(esqlabsR)

setwd("G:/My Drive/Modeling_Projects/Test/Scripts")
```

```{r}
myProjectConfiguration <-
  createProjectConfiguration("../ProjectConfiguration.xlsx")

# Create `ScenarioConfiguration` objects from excel files
scenarioConfigurations <- readScenarioConfigurationFromExcel(
  scenarioNames = NULL,
  projectConfiguration = myProjectConfiguration
)

# Create simulation scenarios defined in the excel files and apply the custom parameters
myScenarios <- createScenarios(
  scenarioConfigurations = scenarioConfigurations)

# Adjust simulation run options, if necessary.
# E.g. disable check for negative values if required
simulationRunOptions <- ospsuite::SimulationRunOptions$new()
simulationRunOptions$checkForNegativeValues <- FALSE

# Run simulations
simulatedScenariosResults <- runScenarios(
  scenarios = myScenarios,
  simulationRunOptions = simulationRunOptions
)

# Save results and store the path to the results for later re-use
outputFolder <- saveScenarioResults(simulatedScenariosResults, myProjectConfiguration)
 
```